#! /bin/sh
DIR=`dirname $0`
NEDPATH=$DIR/../tutorials:$DIR/../examples:$DIR/../samples:$DIR

# prepare for INET compiled as executable and as shared library
if [ -f $DIR/INET -o -f $DIR/INET.exe ]; then
  COMMAND=$DIR/INET
else
  COMMAND="opp_run -l $DIR/INET"
fi

# start with valgrind if the first argument is --valgrind
if [ "$1" = "--valgrind" ] ; then
   shift
   echo "##### Running with Valgrind! ######"
   VALGRIND_OPTIONS="-v --tool=memcheck --leak-check=yes --show-reachable=no --leak-resolution=high --num-callers=40 --freelist-vol=4000000"
   COMMAND="valgrind $VALGRIND_OPTIONS $COMMAND"
fi

# run the simulation
#echo $COMMAND -n $NEDPATH "$@"
$COMMAND -n $NEDPATH "$@"

