name: Build and tests

on:
  schedule:
      # https://crontab.guru/#0_21_*_*_1-5
    - cron: "0 21 * * 1-5" # "At 21:00 on every day-of-week from Monday through Friday."
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    # nothing

jobs:

  check-for-redundancy:
    name: Check for redundancy
    runs-on: ubuntu-latest
    outputs:
      skip-this-run: ${{ env.SKIP_THIS_RUN }}
    steps:
      - name: Redundancy check
        run: |
          :
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
             echo "Skipping redundancy check: workflow was triggered manually"
          else
            CHECK_RUNS_TOTAL_COUNT=$(curl -s "https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/check-runs?status=completed" | jq ".total_count")
            if [ $CHECK_RUNS_TOTAL_COUNT -gt 0 ]; then
              echo "This run would be redundant"
              echo "SKIP_THIS_RUN=true" >> $GITHUB_ENV
            fi
          fi
        shell: bash

  build-native:
    needs: check-for-redundancy
    if: needs.check-for-redundancy.outputs.skip-this-run != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: ["debug", "release"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Pull Docker image
        run: docker pull omnetpp/travis-inet:6.0pre10-201218
      - name: Build (native)
        run: |
          docker run -i --env TARGET_PLATFORM=linux --env MODE=${{ matrix.mode }} --env GITHUB_WORKSPACE \
            -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            omnetpp/travis-inet:6.0pre10-201218 /bin/bash $GITHUB_WORKSPACE/_scripts/github/github-job-build.sh
      - uses: actions/upload-artifact@v2
        with:
          name: libinet-so
          path: ${{ github.workspace }}/src/libINET*.so

  build-cross:
    needs: check-for-redundancy
    if: needs.check-for-redundancy.outputs.skip-this-run != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["windows", "macosx"]
        mode: ["debug", "release"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Pull Docker image
        run: docker pull omnetpp/travis-inet:6.0pre10-201218
      - name: Build (cross)
        run: |
          docker run -i --env TARGET_PLATFORM=${{ matrix.target }} --env MODE=${{ matrix.mode }} --env GITHUB_WORKSPACE \
            -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            omnetpp/travis-inet:6.0pre10-201218 /bin/bash $GITHUB_WORKSPACE/_scripts/github/github-job-build.sh

  fingerprints:
    needs: build-native
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode: ["debug", "release"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: libinet-so
          path: ${{ github.workspace }}/src/
      - name: Pull Docker image
        run: docker pull omnetpp/travis-inet:6.0pre10-201218
      - name: Fingerprint tests
        run: |
          docker run -i --env MODE=${{ matrix.mode }} --env GITHUB_WORKSPACE \
            -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            omnetpp/travis-inet:6.0pre10-201218 /bin/bash $GITHUB_WORKSPACE/_scripts/github/github-job-fingerprints.sh

  other-tests:
    needs: build-native
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO: add debug/release mode when the runtest scripts can switch between
        # MODEs or executables based on command line arguments or envvars
        testdir: ["module", "unit", "packet", "queueing", "protocol",
                  "packetdrill/udp", "packetdrill/tcp", "packetdrill/sctp"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: libinet-so
          path: ${{ github.workspace }}/src/
      - name: Pull Docker image
        run: docker pull omnetpp/travis-inet:6.0pre10-201218
      - name: Run ${{ matrix.testdir }} tests
        run: |
          docker run -i --env MODE=debug --env GITHUB_WORKSPACE --env TESTDIR=${{ matrix.testdir }} \
            -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE \
            omnetpp/travis-inet:6.0pre10-201218 /bin/bash $GITHUB_WORKSPACE/_scripts/github/github-job-other-tests.sh

