name: "Test: chart"

on:
  schedule:
      # https://crontab.guru/#0_16_*_*_6
    - cron: "0 16 * * 6" # “At 16:00 on Saturday.”
  workflow_dispatch:
    # nothing

jobs:
  main:
    runs-on: self-hosted
    # runs-on: [self-hosted, linux]
    strategy:
      matrix:
        mode: ["release"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          repository: omnetpp/omnetpp
          path: omnetpp
      - uses: actions/checkout@v3
        with:
          path: inet
      - run: mkdir -p /home/runner/work/ccache
      - uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/ccache
          key: native-${{ matrix.mode }}-ccache-${{ github.run_id }}
          # See: https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
          restore-keys: native-${{ matrix.mode }}-ccache
      - name: Run main
        env:
          MODE: ${{ matrix.mode }}
        run: |
          echo "::group::Installing packages"
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git wget curl ca-certificates \
            make ccache pkg-config clang lld gdb bison flex perl doxygen graphviz libxml2-dev zlib1g-dev \
            libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libz3-dev libopenscenegraph-dev \
            python3 libpython3-dev python3-pip python3-pandas python3-numpy python3-matplotlib \
            python3-scipy python3-seaborn python3-posix-ipc
          echo "::endgroup::"

          source $GITHUB_WORKSPACE/inet/_scripts/github/build-omnetpp.sh

          echo "::group::Installing pip"
          sudo apt install -y python3-pip
          echo "::endgroup::"

          echo "::group::Installing Python packages"
          python3 -m pip install --upgrade matplotlib numpy pandas scipy ipython cppyy sewar dask distributed IPython optimparallel
          echo "::endgroup::"

          source $GITHUB_WORKSPACE/inet/_scripts/github/build-inet.sh

          echo "::group::Cloning inet media repository"
          git clone https://github.com/inet-framework/media.git
          echo "::endgroup::"

          echo "::group::Running chart tests"
          inet_run_chart_tests -m release -f showcases
          echo "::endgroup::"
      - uses: actions/upload-artifact@v3
        if: always() # even if the test failed, of course
        with:
          name: chart-test-results
          path: |
            ${{ github.workspace }}/inet/media/**/*_new.png
            ${{ github.workspace }}/inet/media/**/*_diff.png
          if-no-files-found: ignore
