name: "Build: native"

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
  workflow_dispatch:
    # nothing

jobs:
  main:
    runs-on: self-hosted
    strategy:
      matrix:
        mode: ["debug", "release"]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: omnetpp/omnetpp
          path: omnetpp
      - uses: actions/checkout@v3
        with:
          path: inet
      - run: mkdir -p /home/runner/work/ccache
      - uses: actions/cache@v3
        with:
          path: /home/runner/work/ccache
          key: native-${{ matrix.mode }}-ccache-${{ github.run_id }}
          # See: https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
          restore-keys: native-${{ matrix.mode }}-ccache
      - name: Build
        env:
          MODE: ${{ matrix.mode }}
        run: |
          echo "::group::Installing packages"
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git wget curl ca-certificates \
            make ccache clang lld gdb bison flex perl doxygen graphviz libxml2-dev zlib1g-dev \
            libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libz3-dev \
            libopenscenegraph-dev python3 libpython3-dev
          echo "::endgroup::"

          source $GITHUB_WORKSPACE/inet/_scripts/github/build-omnetpp.sh

          source $GITHUB_WORKSPACE/inet/_scripts/github/build-inet.sh
