name: "Test: validation"

on:
  schedule:
    - cron: "0 21 * * 1-5" # https://crontab.guru/#0_21_*_*_1-5 : "At 21:00 on every day-of-week from Monday through Friday."
  workflow_dispatch:
    # nothing

jobs:
  activity-check:
    name: Activity check
    runs-on: ubuntu-20.04
    outputs:
      is_active: ${{ steps.activity.outputs.is_active }}

    steps:
      - uses: actions/checkout@v3
      - name: Check for repo activity
        id: activity
        run: |
          # Skip activity check when manually triggered.
          if [ "${{ github.event_name }}" == "repository_dispatch" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            is_active=true
          elif [ "$(git rev-list --after="24 hours" ${{ github.sha }})" ]; then
            is_active=true
          else
            is_active=false
          fi
          echo "is_active=$is_active" >> $GITHUB_OUTPUT

  main:
    needs: activity-check
    runs-on: ubuntu-20.04
    # runs-on: [self-hosted, linux]
    strategy:
      matrix:
        mode: ["release"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          repository: omnetpp/omnetpp
          path: omnetpp
      - uses: actions/checkout@v3
        with:
          path: inet
      - run: mkdir -p /home/runner/work/ccache
      - uses: actions/cache/restore@v3
        with:
          path: /home/runner/work/ccache
          key: native-${{ matrix.mode }}-ccache-${{ github.run_id }}
          # See: https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
          restore-keys: native-${{ matrix.mode }}-ccache
      - name: Build and test
        env:
          MODE: ${{ matrix.mode }}
        run: |
          echo "::group::Installing packages"
          sudo apt-get install -y --no-install-recommends git wget curl ca-certificates \
            make ccache clang lld gdb bison flex perl doxygen graphviz libxml2-dev zlib1g-dev \
            libavcodec-dev libavformat-dev libavutil-dev libswresample-dev libz3-dev libopenscenegraph-dev \
            python3 python3-pip python3-pandas python3-numpy python3-matplotlib \
            python3-scipy python3-seaborn python3-posix-ipc
          echo "::endgroup::"

          source $GITHUB_WORKSPACE/inet/_scripts/github/build-omnetpp.sh

          echo "::group::Installing pip"
          sudo apt install -y python3-pip
          echo "::endgroup::"

          echo "::group::Installing Python packages"
          python3 -m pip install --upgrade matplotlib numpy pandas scipy ipython cppyy sewar dask distributed IPython optimparallel
          echo "::endgroup::"

          source $GITHUB_WORKSPACE/inet/_scripts/github/build-inet.sh

          echo "::group::Running validation tests"
          inet_run_validation_tests -m release
          echo "::endgroup::"
